# ./docker-compose.yml
networks:
  app-tier:
    driver: bridge

services:
  mysql:
    build:
      context: ./
      dockerfile: ./bin/docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ynot_site
      MYSQL_USER: ynot_sql_user
      MYSQL_PASSWORD: ynot_sql_pass
    networks:
      - app-tier
    volumes:
      - 'mysqldb_data:/bitnami'
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:latest'
    ports:
      - '8181:8181'
    depends_on:
      - mysql
    environment:
      - APACHE_HTTP_PORT_NUMBER=8181
      - DATABASE_HOST=mysql
    networks:
      - app-tier
  phpfpm:
    image: docker.io/bitnami/php-fpm:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - app-tier
    volumes:
      - ./src:/app
  apache:
    image: docker.io/bitnami/apache:latest
    ports:
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - mysql
      - phpfpm
    volumes:
      - type: bind
        source: ./bin/docker/apache-vhost/my_vhost.conf
        target: /opt/bitnami/apache/conf/vhosts/my_vhost.conf
      - ./src:/app
volumes:
  mysqldb_data:
    driver: local