#!/usr/bin/env bash
#
# Bakes the per-deploy origin into a committed-into-bundle TS module so Payload
# CSRF/CORS accepts the dynamic branch/preview origin.
#
# Why a generated module instead of an env var:
#   Netlify exposes DEPLOY_PRIME_URL (the exact branch/preview origin, e.g.
#   https://my-branch--site.netlify.app) ONLY during the build, NOT at function
#   runtime where payload.config.ts executes — confirmed via a runtime probe that
#   showed DEPLOY_PRIME_URL/CONTEXT/BRANCH all null. process.env reads at runtime
#   would never see it. Writing the value into a TS literal that payload.config.ts
#   statically imports freezes it into the serverless bundle, so it survives.
#
# Payload's CSRF check is an exact string match (no globs), so each deploy needs
# its specific origin added. On production (DEPLOY_PRIME_URL unset) this is a
# no-op and the default empty origin is written.

set -euo pipefail

ORIGIN="${DEPLOY_PRIME_URL:-}"
OUT="payload/generated/deploy-origin.ts"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
// AUTO-GENERATED by scripts/netlify-bake-deploy-origin.sh at build time.
// Holds the Netlify per-deploy origin (DEPLOY_PRIME_URL) which is unavailable
// at function runtime. Do not edit by hand.
export const DEPLOY_ORIGIN = '${ORIGIN}';
EOF

if [ -n "$ORIGIN" ]; then
  echo "netlify-bake-deploy-origin: baked DEPLOY_ORIGIN=$ORIGIN"
else
  echo "netlify-bake-deploy-origin: DEPLOY_PRIME_URL unset (production) — wrote empty origin."
fi
