#!/usr/bin/env bash
# .buildkite/scripts/combine-integrity-reports.sh
# Downloads individual integrity check artifacts, combines them,
# and posts the result to a GitHub issue.

set -euo pipefail

echo "--- :yarn: Installing dependencies"
corepack enable && yarn install --immutable

echo "--- :file_folder: Downloading integrity check artifacts"
buildkite-agent artifact download "integrity-*.md" /tmp/ || true

echo "--- :bar_chart: Combining reports"
{
  echo "# Nightly Content Integrity Report"
  echo ""
  echo "_Generated by Buildkite build #${BUILDKITE_BUILD_NUMBER}_"
  echo ""
  for report in \
    /tmp/integrity-display-names.md \
    /tmp/integrity-slugs.md \
    /tmp/integrity-musicbrainz.md \
    /tmp/integrity-record-metadata.md \
    /tmp/integrity-ondemand-source.md \
    /tmp/integrity-publish-status.md; do
    if [ -f "$report" ]; then
      echo ""
      cat "$report"
      echo ""
      echo "---"
    else
      BASENAME=$(basename "$report" .md)
      echo ""
      echo "## ${BASENAME}"
      echo ""
      echo "⚠️ Report not available (check may have failed)"
      echo ""
      echo "---"
    fi
  done
} > /tmp/integrity-combined-report.md

echo "--- :github: Posting integrity report"
if [ -n "${INTEGRITY_REPORT_ISSUE_NUMBER:-}" ]; then
  node .buildkite/scripts/update-integrity-report-issue.mjs /tmp/integrity-combined-report.md
else
  echo "⚠️ INTEGRITY_REPORT_ISSUE_NUMBER not set, skipping GitHub issue update"
  cat /tmp/integrity-combined-report.md
fi
