#!/usr/bin/env bash
# .buildkite/scripts/run-integrity-checks.sh
# Runs 6 content integrity checks against Neon prod, combines reports,
# and posts the result to a GitHub issue.
# Called by nightly-gap-report.yml — extracted from inline YAML for readability.

set -euo pipefail

echo "--- :yarn: Installing dependencies"
corepack enable && yarn install --immutable

export DATABASE_URI="$NEON_PROD_DATABASE_URL"

PRELOAD="--import ./bin/preload-nextenv-fix.mjs --import tsx"

echo "--- :bust_in_silhouette: Checking display names"
node $PRELOAD bin/integrity-check-display-names.ts \
  --since 25h --output /tmp/integrity-display-names.md --verbose || true

echo "--- :link: Checking slugs"
node $PRELOAD bin/integrity-check-slugs.ts \
  --since 25h --output /tmp/integrity-slugs.md --verbose || true

echo "--- :musical_note: Checking MusicBrainz associations"
node $PRELOAD bin/integrity-check-musicbrainz.ts \
  --skip-type-check --since 25h --output /tmp/integrity-musicbrainz.md --verbose || true

echo "--- :cd: Checking record metadata"
node $PRELOAD bin/integrity-check-record-metadata.ts \
  --since 25h --output /tmp/integrity-record-metadata.md --verbose || true

echo "--- :radio: Checking OnDemand source fields"
node $PRELOAD bin/integrity-check-ondemand-source.ts \
  --from prod-mysql --since 25h --output /tmp/integrity-ondemand-source.md --verbose || true

echo "--- :white_check_mark: Checking publish status"
node $PRELOAD bin/integrity-check-publish-status.ts \
  --from prod-mysql --since 25h --output /tmp/integrity-publish-status.md --verbose || true

echo "--- :bar_chart: Combining reports"
{
  echo "# Nightly Content Integrity Report"
  echo ""
  echo "_Generated by Buildkite build #${BUILDKITE_BUILD_NUMBER}_"
  echo ""
  for report in /tmp/integrity-display-names.md /tmp/integrity-slugs.md /tmp/integrity-musicbrainz.md /tmp/integrity-record-metadata.md /tmp/integrity-ondemand-source.md /tmp/integrity-publish-status.md; do
    if [ -f "$report" ]; then
      echo ""
      cat "$report"
      echo ""
      echo "---"
    fi
  done
} > /tmp/integrity-combined-report.md

echo "--- :github: Posting integrity report"
if [ -n "$INTEGRITY_REPORT_ISSUE_NUMBER" ]; then
  node .buildkite/scripts/update-integrity-report-issue.mjs /tmp/integrity-combined-report.md
else
  echo "⚠️ INTEGRITY_REPORT_ISSUE_NUMBER not set, skipping GitHub issue update"
  cat /tmp/integrity-combined-report.md
fi
