#!/usr/bin/env bash
# .buildkite/scripts/run-integrity-checks.sh
# Runs the remaining nightly content integrity check (publish-status only) against Neon prod,
# combines reports,
# and posts the result to a GitHub issue.
# Called by nightly-gap-report.yml — extracted from inline YAML for readability.

set -euo pipefail

echo "--- :yarn: Installing dependencies"
corepack enable && yarn install --immutable

export DATABASE_URI="$NEON_PROD_DATABASE_URL"

PRELOAD="--import ./bin/preload-nextenv-fix.mjs --import tsx"

echo "--- :white_check_mark: Checking publish status"
node $PRELOAD bin/integrity-check-publish-status.ts \
  --from prod-mysql --collection posts --since 25h --output /tmp/integrity-publish-status.md --verbose || true

echo "--- :bar_chart: Combining reports"
{
  echo "# Nightly Content Integrity Report"
  echo ""
  echo "_Generated by Buildkite build #${BUILDKITE_BUILD_NUMBER}_"
  echo ""
  for report in /tmp/integrity-publish-status.md; do
    if [ -f "$report" ]; then
      echo ""
      cat "$report"
      echo ""
      echo "---"
    fi
  done
} > /tmp/integrity-combined-report.md

echo "--- :github: Posting integrity report"
if [ -n "$INTEGRITY_REPORT_ISSUE_NUMBER" ]; then
  node .buildkite/scripts/update-integrity-report-issue.mjs /tmp/integrity-combined-report.md
else
  echo "⚠️ INTEGRITY_REPORT_ISSUE_NUMBER not set, skipping GitHub issue update"
  cat /tmp/integrity-combined-report.md
fi
